### ISSUE TITLE
Missing NuGet Package Info or Binary References

### ISSUE THREAD

**Issue by jbienz** [mattw01/TeslaCamViewer#1]
I forked the repo tonight to check it out. When I opened it in Visual Studio I got the following errors:

- The tag 'MetroWindow' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'.

- The referenced component 'MahApps.Metro' could not be found.

- The referenced component 'System.Windows.Interactivity' could not be found.

- The referenced component 'ControlzEx' could not be found.

- Could not locate the assembly "System.Windows.Interactivity, Version=4.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL"

- Could not locate the assembly "MahApps.Metro"

And the binaries are missing from the references panel:

![image](https://user-images.githubusercontent.com/2062886/56702075-cb7cf580-66c7-11e9-9a91-094956974aa6.png)

This could be because binaries are excluded from your .gitignore, or it could be because your NuGet packages json file is excluded in your .gitignore.

**Comment by jbienz** [comment]
Interesting. When I went into the NuGet Package Manager it showed that I could restore the missing packages. I don't know why it didn't do that automatically on build. This may not be something missing after all...?

**Comment by mattw01** [comment]
That is interesting, I pulled a clean repository version and it restored the NuGet packages on build. Not sure why it manually needed to be restored on your end but good to hear it's working now.

**Comment by jbienz** [comment]
Sounds good. Closing this issue.
