### ISSUE TITLE
Feature Request: Maximize Camera

### ISSUE THREAD

**Issue by jbienz** [mattw01/TeslaCamViewer#5]
I'd like to see a maximize button on each camera feed that would allow you to temporarily make that feed take up the entire viewable area.

**Comment by mattw01** [comment]
Thanks for the suggestion! I was thinking about this for a bit trying to figure out the best way to implement this. For now in the v0.4 release it'll resize the grid rows/columns to make the target video cover the viewable area. There might be a better way to do this, but this seems to be functioning for now.
