### ISSUE TITLE
Stuck on "Searching for Teslacam"

### ISSUE THREAD

**Issue by obijan42** [mattw01/TeslaCamViewer#6]
When opening the app on Win10Pro 64, it hangs when searching for the files.

Are you scanning every subdirectory you can find?  Or just the root levels?

Request:  Allow specification of drive letter, either in UI or config file.

**Comment by mattw01** [comment]
This issue should be fixed in V0.4.1. Thanks for reporting this. I'll look into a manual option for specifying a drive to search.

**Comment by mkurzdorfer** [comment]
Opened v0.4.1 and I am experiencing the same issue.  Win10 x64 Build 1903.   I don't see any activity (CPU/Disk) from the TeslaCamViewer.exe.  Memory hovering around 22-24 MB.

**Comment by leonard4** [comment]
Same issue running v0.4.1 as of today. Windows 10 x64 (1809). 

![stuck](https://user-images.githubusercontent.com/1154391/57240616-c5e6b000-6fe3-11e9-9e69-2977d2170441.png)

Posted a fix in an open issue thread.
